version: '3'

vars:
  MAIN_DIR: ./cmd/web/
  PROTO_DIR: ./proto

tasks:
  build:
    cmds:
      - go build -o ./bin/ {{.MAIN_DIR}}

  test:
    cmds:
      - go test {{.CLI_ARGS}} -race ./...

  run:
    cmds:
      - go run {{.CLI_ARGS}} {{.MAIN_DIR}}

  clean:
    cmds:
      - rm -rf ./bin/

  setup:
    cmds:
      # Ensures go.mod is tidy
      - go mod tidy
      # Downloads any missing dependencies
      - go mod download

  format:
    cmds:
      - gofmt -s -w {{.MAIN_DIR}}

  vet:
    cmds:
      - go vet {{.MAIN_DIR}}...

  vuln:
    cmds:
      - govulncheck -test {{.MAIN_DIR}}...

  cert:
    cmds:
      - cd ./cert && ./gen.sh

  gen-proto:
    cmds:
      - buf generate ./proto/

  gen-sql:
    cmds:
      - sqlc generate

  gen-enums:
    cmds:
      - goenums ./goenums.yaml

  gen:
    deps:
      - gen-proto
      - gen-sql
      - gen-enums

  all:
    deps:
      - setup
      - gen
      - format
      - vet
      - vuln
      - test
      - build