package data

import "fmt"

// This file is generated by goenums; DO NOT EDIT

// PrivacySetting wraps an enum value of type privacySetting to enforce type safety.
type PrivacySetting struct {
	privacySetting
}

// privacySetting is the underlying type of PrivacySetting and should not be used directly.
type privacySetting int

const (
	unknownPrivacySetting privacySetting = iota
	publicPrivacySetting
	privatePrivacySetting
)

var (
	strPrivacySettingArray = [...]string{
		publicPrivacySetting:  "PUBLIC",
		privatePrivacySetting: "PRIVATE",
	}

	typePrivacySettingMap = map[string]privacySetting{
		"PUBLIC":  publicPrivacySetting,
		"PRIVATE": privatePrivacySetting,
	}
)

// String returns the string representation of the enum value
func (p privacySetting) String() string {
	return strPrivacySettingArray[p]
}

// ParsePrivacySetting attempts to parse the given value into PrivacySetting.
// It supports string, fmt.Stringer, int, int64, and int32.
// If the value is not a valid PrivacySetting or the value is not a supported type, it will return the enums unknown value (unknownPrivacySetting).
func ParsePrivacySetting(a any) PrivacySetting {
	switch v := a.(type) {
	case PrivacySetting:
		return v
	case string:
		return PrivacySetting{stringToPrivacySetting(v)}
	case fmt.Stringer:
		return PrivacySetting{stringToPrivacySetting(v.String())}
	case int:
		return PrivacySetting{privacySetting(v)}
	case int64:
		return PrivacySetting{privacySetting(int(v))}
	case int32:
		return PrivacySetting{privacySetting(int(v))}
	}
	return PrivacySetting{unknownPrivacySetting}
}

// stringToPrivacySetting attempts to parse the given string into PrivacySetting.
// If the value is not a valid PrivacySetting, it will return the enums unknown value (unknownPrivacySetting).
func stringToPrivacySetting(s string) privacySetting {
	if v, ok := typePrivacySettingMap[s]; ok {
		return v
	}
	return unknownPrivacySetting
}

// IsValid returns true if the enum value is valid.
// The unknown value (unknownPrivacySetting) is not considered valid.
func (p privacySetting) IsValid() bool {
	return p >= privacySetting(1) && p <= privacySetting(len(strPrivacySettingArray))
}

// PrivacySettingContainer contains all possible values of type PrivacySetting.
type PrivacySettingContainer struct {
	UNKNOWN PrivacySetting
	PUBLIC  PrivacySetting
	PRIVATE PrivacySetting
}

// PrivacySettings is a global instance of PrivacySettingContainer that contains all possible values of type PrivacySetting.
var PrivacySettings = PrivacySettingContainer{
	UNKNOWN: PrivacySetting{unknownPrivacySetting},
	PUBLIC:  PrivacySetting{publicPrivacySetting},
	PRIVATE: PrivacySetting{privatePrivacySetting},
}

// All returns a slice containing all possible values of type PrivacySetting.
func (c PrivacySettingContainer) All() []PrivacySetting {
	return []PrivacySetting{
		c.PUBLIC,
		c.PRIVATE,
	}
}

// MarshalJSON returns the JSON representation of the enum value.
func (p *PrivacySetting) MarshalJSON() ([]byte, error) {
	return []byte(`"` + p.String() + `"`), nil
}

// UnmarshalJSON parses the JSON representation of the enum value.
func (p *PrivacySetting) UnmarshalJSON(b []byte) error {
	*p = ParsePrivacySetting(string(b))
	return nil
}
