package data

import "fmt"

// This file is generated by goenums; DO NOT EDIT

//go:generate stringer -type=ResponseStatus -output=responseStatus_string.go
type ResponseStatus struct {
	responseStatus
}

type responseStatus int

const (
	unknownResponseStatus responseStatus = iota
	sentResponseStatus
	seenResponseStatus
	yesResponseStatus
	noResponseStatus
	maybeResponseStatus
)

var (
	strResponseStatusArray = [...]string{
		sentResponseStatus:  "SENT",
		seenResponseStatus:  "SEEN",
		yesResponseStatus:   "YES",
		noResponseStatus:    "NO",
		maybeResponseStatus: "MAYBE",
	}

	typeResponseStatusMap = map[string]responseStatus{
		"SENT":  sentResponseStatus,
		"SEEN":  seenResponseStatus,
		"YES":   yesResponseStatus,
		"NO":    noResponseStatus,
		"MAYBE": maybeResponseStatus,
	}
)

func (r responseStatus) String() string {
	return strResponseStatusArray[r]
}

func ParseResponseStatus(a any) ResponseStatus {
	switch v := a.(type) {
	case ResponseStatus:
		return v
	case string:
		return ResponseStatus{stringToResponseStatus(v)}
	case fmt.Stringer:
		return ResponseStatus{stringToResponseStatus(v.String())}
	case int:
		return ResponseStatus{responseStatus(v)}
	case int64:
		return ResponseStatus{responseStatus(int(v))}
	case int32:
		return ResponseStatus{responseStatus(int(v))}
	}
	return ResponseStatus{unknownResponseStatus}
}

func stringToResponseStatus(s string) responseStatus {
	if v, ok := typeResponseStatusMap[s]; ok {
		return v
	}
	return unknownResponseStatus
}

func (r responseStatus) IsValid() bool {
	return r >= responseStatus(1) && r <= responseStatus(len(strResponseStatusArray))
}

type ResponseStatusContainer struct {
	UNKNOWN ResponseStatus
	SENT    ResponseStatus
	SEEN    ResponseStatus
	YES     ResponseStatus
	NO      ResponseStatus
	MAYBE   ResponseStatus
}

var ResponseStatuses = ResponseStatusContainer{
	UNKNOWN: ResponseStatus{unknownResponseStatus},
	SENT:    ResponseStatus{sentResponseStatus},
	SEEN:    ResponseStatus{seenResponseStatus},
	YES:     ResponseStatus{yesResponseStatus},
	NO:      ResponseStatus{noResponseStatus},
	MAYBE:   ResponseStatus{maybeResponseStatus},
}

func (c ResponseStatusContainer) All() []ResponseStatus {
	return []ResponseStatus{
		c.SENT,
		c.SEEN,
		c.YES,
		c.NO,
		c.MAYBE,
	}
}

func (r *ResponseStatus) MarshalJSON() ([]byte, error) {
	return []byte(`"` + r.String() + `"`), nil
}

func (r *ResponseStatus) UnmarshalJSON(b []byte) error {
	*r = ParseResponseStatus(string(b))
	return nil
}
